name: Compile Codebook
run-name: Compile codebook
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    container: ghcr.io/abc864197532/codebook:latest 
    permissions:
      contents: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check indentation
        run: |
          chmod +x scripts/check_indent.sh
          ./scripts/check_indent.sh

      - name: Compile
        run: |
          cd codebook
          texfot latexmk -xelatex --shell-escape codebook.tex
          cd ..

      - name: Check PDF Page
        run: |
          chmod +x scripts/check_pdf_page.sh
          ./scripts/check_pdf_page.sh

      - name: Commit and Push PDF to build branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: build
          commit_message: build from ${{ github.ref_name }} - ${{ github.sha }}
          file_pattern: codebook/codebook.pdf
